# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
    target-branch: "dependabot-updates"
    open-pull-requests-limit: 3
    
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dependabot-updates"
    open-pull-requests-limit: 3
    
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"  
    target-branch: "dependabot-updates"
    open-pull-requests-limit: 3