# Simplified Dependabot configuration for MedTestAI
version: 2
updates:
  # GitHub Actions dependencies only (this always works)
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "JannetEkka"
    labels:
      - "dependencies"
      - "ci-cd"