name: Healthcare Security CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  compliance-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Basic PHI detection scan
        run: |
          echo "Scanning for potential PHI patterns..."
          if find src/ -name "*.js" -o -name "*.py" -o -name "*.json" 2>/dev/null | xargs grep -l -E "\b\d{3}-\d{2}-\d{4}\b|\b\d{4}\s?\d{4}\s?\d{4}\s?\d{4}\b" 2>/dev/null; then
            echo "⚠️  Potential PHI detected - please review"
            exit 1
          else
            echo "✅ No obvious PHI patterns found"
          fi

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Test GCP healthcare connection
        run: |
          echo "Testing authentication..."
          gcloud auth list
          
          echo "Testing project access..."
          gcloud projects describe ${{ secrets.GCP_PROJECT_ID }}
          
          echo "Testing healthcare dataset connection..."
          gcloud healthcare datasets describe ${{ secrets.HEALTHCARE_DATASET }} --location=us-central1
          
          echo "✅ Healthcare infrastructure connection successful!"